# Generated by Django 2.0.1 on 2018-01-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseMessage',
            new_name='UserMessage',
        ),
    ]
